version: 2
jobs:
    # The build job for staging branches that excludes Google Tag Manager
    build-staging:
        docker:
            - image: cibuilds/hugo:0.48
        working_directory: ~/project
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Declare target location for baseURL and deployment location and build site
            # Improvement-> move the declaration to command and save to bash environment: echo 'export PATH=/path/to/foo/bin:$PATH' >> $BASH_ENV
            - run:
                name: Pull latest master
                command: |
                    git config --global user.email "github@mansheim.com"
                    git config --global user.name "Ben Mansheim"
                    git checkout master
                    git pull
                    git checkout latest-build
                    git rebase master

workflows:
    version: 2
    build-deploy:
        jobs:
            - build-staging